
-- #############################################################################################################
-- FILE: session_sql_bridge.sql
-- #############################################################################################################
--
-- PURPOSE:
-- Bridges application/session identity to SQL_ID by correlating GV$SESSION and GV$SQL using filters
-- (username, module, action, machine, program) to identify offending SQL generated by a workload source.
--
-- INPUT PARAMETERS:
-- &1 (username_like) - STRING - Username filter pattern (e.g., 'APPUSER%'; use '%' for all).
-- &2 (module_like) - STRING - Module filter pattern (e.g., 'JDBC Thin Client%'; use '%' for all).
-- &3 (action_like) - STRING - Action filter pattern (e.g., '%Checkout%'; use '%' for all).
-- &4 (machine_like) - STRING - Machine/host filter pattern (e.g., 'appsrv01%'; use '%' for all).
-- &5 (program_like) - STRING - Program filter pattern (e.g., 'java%'; use '%' for all).
-- &6 (top_n) - NUMBER - Maximum rows to display (e.g., 100).
--
-- OUTPUT DESCRIPTION:
-- Two result sets:
-- 1. Session to SQL Mapping: inst_id, sid/serial, username, module/action, machine/program,
--    sql_id, child cursor, sql_exec_start, status, wait class/event, and elapsed seconds.
-- 2. Aggregated SQL by Source Attributes: grouped SQL_ID counts and elapsed/cpu/io indicators
--    by module/action/machine/program to pinpoint dominant SQL generators.
--
-- QUESTIONS ADDRESSED BY THIS SCRIPT:
-- REM EMBEDDINGS BEG
-- Which SQL_IDs are executed by a specific module/action?
-- Which SQL statements are coming from a specific application server machine?
-- Which SQL_ID is associated with a given username workload?
-- Which active sessions from one program are currently expensive?
-- Is one module producing most of the problematic SQL?
-- What SQL child cursors are used by the same workload source?
-- Are multiple sessions running the same SQL_ID concurrently?
-- Which application source should be contacted for SQL remediation?
-- Can I map workload context to concrete SQL_IDs quickly?
-- Which SQL_ID shortlist corresponds to the observed application slowdown?
-- REM EMBEDDINGS END
--
-- #############################################################################################################
-- EXAMPLE : session_sql_bridge.sql APPUSER% % % appsrv01% java% 100
-- #############################################################################################################

spool session_sql_bridge.log

set pages 9999
set lines 260
set verify off
set trimspool on
set tab off
set feedback on
set termout on

whenever sqlerror exit failure rollback

define username_like = '&1'
define module_like   = '&2'
define action_like   = '&3'
define machine_like  = '&4'
define program_like  = '&5'
define top_n         = '&6'

-- Validate required parameters for session-to-SQL bridge analysis.
declare
  l_top_n number;
begin
  if '&&username_like' is null or '&&module_like' is null or '&&action_like' is null
     or '&&machine_like' is null or '&&program_like' is null or '&&top_n' is null then
    raise_application_error(-20801,
      'Usage: @session_sql_bridge.sql <USERNAME_LIKE> <MODULE_LIKE> <ACTION_LIKE> <MACHINE_LIKE> <PROGRAM_LIKE> <TOP_N>');
  end if;

  l_top_n := to_number('&&top_n');
  if l_top_n < 1 then
    raise_application_error(-20802, 'TOP_N must be >= 1.');
  end if;
end;
/

prompt
prompt =====================================================================================================
prompt Session-to-SQL bridge filters:
prompt USERNAME like &&username_like
prompt MODULE   like &&module_like
prompt ACTION   like &&action_like
prompt MACHINE  like &&machine_like
prompt PROGRAM  like &&program_like
prompt TOP_N=&&top_n
prompt =====================================================================================================

column sid_serial      format a15
column username        format a20
column module          format a30
column action          format a30
column machine         format a30
column program         format a35
column status          format a8
column sql_id          format a13
column child_number    format 99999
column sql_exec_start  format a19
column event           format a45
column wait_class      format a15
column elapsed_s       format 999,999,999.999
column inst_id         format 99999

prompt
prompt --- 1) Session to SQL mapping ---

-- Map filtered live sessions to SQL_ID and runtime context to bridge app source to SQL.
with sess as (
  select s.inst_id,
         s.sid,
         s.serial#,
         s.username,
         nvl(s.module,'(null)') as module,
         nvl(s.action,'(null)') as action,
         nvl(s.machine,'(null)') as machine,
         nvl(s.program,'(null)') as program,
         s.status,
         s.sql_id,
         s.sql_child_number as child_number,
         s.sql_exec_start,
         s.event,
         s.wait_class,
         (sysdate - s.sql_exec_start) * 86400 as elapsed_s
    from gv$session s
   where s.type = 'USER'
     and s.sql_id is not null
     and nvl(s.username,'~') like '&&username_like'
     and nvl(s.module,'~')   like '&&module_like'
     and nvl(s.action,'~')   like '&&action_like'
     and nvl(s.machine,'~')  like '&&machine_like'
     and nvl(s.program,'~')  like '&&program_like'
), ranked as (
  select x.*,
         row_number() over (order by nvl(x.elapsed_s,0) desc, x.inst_id, x.sid) as rn
    from sess x
)
select inst_id,
       sid || ',' || serial# as sid_serial,
       username,
       module,
       action,
       machine,
       program,
       status,
       sql_id,
       child_number,
       to_char(sql_exec_start, 'yyyy-mm-dd hh24:mi:ss') as sql_exec_start,
       wait_class,
       event,
       round(elapsed_s,3) as elapsed_s
  from ranked
 where rn <= to_number('&&top_n')
 order by rn;

column session_count   format 999,999,999
column active_count    format 999,999,999
column execs           format 999,999,999,999
column elapsed_s       format 999,999,999,990.999
column cpu_s           format 999,999,999,990.999
column lio             format 999,999,999,999,999
column pio             format 999,999,999,999,999

prompt
prompt --- 2) Aggregated SQL by source attributes ---

-- Aggregate source attributes to identify which module/action/machine/program drives expensive SQL.
with sess as (
  select nvl(s.module,'(null)')  as module,
         nvl(s.action,'(null)')  as action,
         nvl(s.machine,'(null)') as machine,
         nvl(s.program,'(null)') as program,
         s.sql_id,
         s.status
    from gv$session s
   where s.type = 'USER'
     and s.sql_id is not null
     and nvl(s.username,'~') like '&&username_like'
     and nvl(s.module,'~')   like '&&module_like'
     and nvl(s.action,'~')   like '&&action_like'
     and nvl(s.machine,'~')  like '&&machine_like'
     and nvl(s.program,'~')  like '&&program_like'
),
metrics as (
  select q.sql_id,
         sum(q.executions) as execs,
         sum(q.elapsed_time)/1e6 as elapsed_s,
         sum(q.cpu_time)/1e6 as cpu_s,
         sum(q.buffer_gets) as lio,
         sum(q.disk_reads) as pio
    from gv$sql q
   group by q.sql_id
),
agg as (
  select s.module,
         s.action,
         s.machine,
         s.program,
         s.sql_id,
         count(*) as session_count,
         sum(case when s.status = 'ACTIVE' then 1 else 0 end) as active_count,
         nvl(max(m.execs),0) as execs,
         nvl(max(m.elapsed_s),0) as elapsed_s,
         nvl(max(m.cpu_s),0) as cpu_s,
         nvl(max(m.lio),0) as lio,
         nvl(max(m.pio),0) as pio
    from sess s
    left join metrics m
      on m.sql_id = s.sql_id
   group by s.module, s.action, s.machine, s.program, s.sql_id
), ranked as (
  select a.*,
         row_number() over (order by a.elapsed_s desc, a.session_count desc) as rn
    from agg a
)
select module,
       action,
       machine,
       program,
       sql_id,
       session_count,
       active_count,
       execs,
       round(elapsed_s,3) as elapsed_s,
       round(cpu_s,3) as cpu_s,
       lio,
       pio
  from ranked
 where rn <= to_number('&&top_n')
 order by rn;

spool off

exit;
